[project]
name = "lekturai-back"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.121.2",
    "mypy>=1.18.2",
    "ollama>=0.6.1",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.38.0",
]

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
plugins = ["pydantic.mypy"]
